name: Linting Pipeline

# Trigger on pushes and PRs targeting develop
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3) Install linting tools
      - name: Install HTMLHint & Stylelint
        run: npm install --save-dev htmlhint stylelint stylelint-config-standard

      # 4) Run HTMLHint against all .html files
      - name: HTMLHint
        run: npx htmlhint "**/*.html" --config .htmlhintrc.json

      # 5) Run Stylelint against all .css files
      - name: Stylelint
        run: npx stylelint "**/*.css" --config .stylelintrc.json
