name: Linting Pipeline

# Trigger on pushes and PRs targeting develop
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3) Install linting tools
      - name: Install HTMLHint & Stylelint
        run: npm install --save-dev htmlhint stylelint stylelint-config-standard

      # 4) Run HTMLHint against all .html files
      - name: HTMLHint
        run: npx htmlhint "**/*.html" --config .htmlhintrc.json

      # 5) Run Stylelint against all .css files (allow no matches)
      - name: Stylelint
        run: npx --yes stylelint "**/*.css" --config .stylelintrc.json --allow-empty-input

      # 6) Upload linting artifacts (configs & any logs)
      - name: Upload linting results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            .htmlhintrc.json
            .stylelintrc.json
            npm-debug.log   # if npm errors, its log gets uploaded
